# see https://github.com/compose-spec/compose-spec/blob/master/spec.md
# see https://github.com/opencontainers/image-spec/blob/master/annotations.md
services:
  aspire-dashboard:
    # see https://learn.microsoft.com/en-us/dotnet/aspire/fundamentals/dashboard/overview
    # see https://mcr.microsoft.com/product/dotnet/aspire-dashboard/about
    # see https://github.com/dotnet/dotnet-docker/issues/5128
    # see https://github.com/dotnet/aspire/issues/3407
    # see https://github.com/dotnet/aspire/tree/main/src/Aspire.Dashboard
    image: mcr.microsoft.com/dotnet/aspire-dashboard:8.0
    environment:
      - DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS=true
    ports:
      # web ui.
      - 18888:18888
      # otlp grpc.
      #- 18889:18889
    restart: on-failure
  quotes:
    build: quotes
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://aspire-dashboard:18889
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - ASPNETCORE_URLS=http://+:8000
      - QUOTES_BASE_URL=http://quotes:8000
    ports:
      # http api.
      # http://localhost:8000
      - 8000:8000
    healthcheck:
      test: ["CMD", "curl", "--silent", "--fail-with-body", "--max-time", "5", "http://localhost:8000/healthz/ready"]
      interval: 15s
      timeout: 5s
      retries: 2
    restart: on-failure
